# Generated by Django 4.1.7 on 2023-04-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asociados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_familia', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=30)),
                ('DNI', models.CharField(max_length=8)),
                ('integrantes', models.CharField(max_length=2)),
                ('mascotas', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Terrenos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=40)),
                ('DNI', models.CharField(max_length=8)),
            ],
        ),
    ]
